attendees:
  label: Attendees

  view:
    toolbarButtons: create|add|remove

    list:
      columns:
        name:

  manage:
    form: $/ncarps/bookings/models/attendee/fields.yaml

  pivot:
    form:
      fields:
        name:
          label: Name